apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../config/default

images:
  - name: controller
    newName: ooto
    newTag: local

patchesStrategicMerge:
  - |
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: controller-manager
      namespace: system
    spec:
      template:
        spec:
          nodeSelector:
            # This is the node we're building the ooto:local image on
            kubernetes.io/hostname: minikube
          containers:
            - name: manager
              imagePullPolicy: Never
