#!/bin/sh

NS="${NS:-oot-operator-system}"
TIMESTAMP=$(date +%Y%m%d_%H%M%S)
OUTPUT_DIR="${OUTPUT_DIR:-must-gather/${TIMESTAMP}}"

for resource in $(oc get all -n $NS --no-headers | awk '{print $1}'); do

  type=$(echo "$resource" | cut -d'/' -f1 )
  name=$(echo "$resource" | cut -d'/' -f2 )

  echo "Inspecting ${resource}"
  oc adm inspect -n "$NS" "$resource" --dest-dir="$OUTPUT_DIR/inspect"

  echo "Collecting information for ${resource}"
  describeFile="${OUTPUT_DIR}/${type}_${name}.yaml"
  oc -n "$NS" describe "$resource" > "$describeFile"
done

echo "Collecting logs from 'deployment/oot-operator-controller-manager'"
oc -n "$NS" logs "deployment/oot-operator-controller-manager" > "${OUTPUT_DIR}/oot-operator-controller-manager.log"

echo "Inspecting modules.ooto.sigs.k8s.io in all the namespaces"
oc adm inspect -A crd/modules.ooto.sigs.k8s.io  --dest-dir="$OUTPUT_DIR/inspect"
