---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - apps
  resources:
  - daemonsets
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - list
  - watch
- apiGroups:
  - ooto.sigs.k8s.io
  resources:
  - modules
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ooto.sigs.k8s.io
  resources:
  - modules/finalizers
  verbs:
  - update
- apiGroups:
  - ooto.sigs.k8s.io
  resources:
  - modules/status
  verbs:
  - get
  - patch
  - update
