name: Collect troubleshooting data

runs:
  using: composite
  steps:
    - name: Get all resources in the oot-operator-system namespace
      run: kubectl get all -n oot-operator-system

    - name: Get all resources in the default namespace
      run: kubectl get all

    - name: Describe nodes
      run: kubectl describe node

    - name: Describe DaemonSets
      run: kubectl describe daemonset -l oot.node.kubernetes.io/module.name

    - name: Describe Pods
      run: kubectl describe pod -l oot.node.kubernetes.io/module.name

    - name: Collect dmesg
      run: sudo dmesg

    - name: Get all operator logs
      run: kubectl logs deployment.apps/oot-operator-controller-manager -n oot-operator-system
