---
apiVersion: ooto.sigs.k8s.io/v1beta1
kind: Module
metadata:
  name: NAME_CHANGEME
spec:
  driverContainer:
    name: overwritten-anyway
    command: [sleep, infinity]
    imagePullPolicy: Never
    lifecycle:
      postStart:
        exec:
          command: [modprobe, -D, /opt, -v, KMOD_CHANGEME]
      preStop:
        exec:
          command: [modprobe, -D, /opt, -rv, KMOD_CHANGEME]
    securityContext:
      capabilities:
        add: [SYS_MODULE]
  kernelMappings:
    - literal: KVER_CHANGEME
      containerImage: ooto-kmod:local
  selector:
    wants-oot-module: KMOD_CHANGEME
