---
apiVersion: ooto.sigs.k8s.io/v1alpha1
kind: Module
metadata:
  name: ooto-ci-build
spec:
  driverContainer:
    name: overwritten-anyway
    command:
      - sh
      - -c
      # Wrap inside echo to disable stdout buffering
      - 'echo "Hello World! secret: $(cat /ci-build-secret)" && sleep infinity'
    lifecycle:
      postStart:
        exec:
          command: [modprobe, -vd, /opt, ooto_ci_a]
      preStop:
        exec:
          command: [modprobe, -rvd, /opt, ooto_ci_a]
    securityContext:
      capabilities:
        add: [SYS_MODULE]
  kernelMappings:
    - literal: KVER_CHANGEME
      containerImage: registry.minikube/ooto-kmod:local
      build:
        pull:
          insecure: true
        push:
          insecure: true
        secrets:
          - name: build-secret
        dockerfile: |
          FROM registry.minikube/ooto-base:local
          RUN cat /run/secrets/build-secret/ci-build-secret > /ci-build-secret
  selector:
    kubernetes.io/hostname: minikube
