---
apiVersion: kmm.sigs.k8s.io/v1beta1
kind: Module
metadata:
  name: ooto-ci
spec:
  moduleLoader:
    container:
      modprobe:
        moduleName: ooto_ci_a
      imagePullPolicy: Never
      kernelMappings:
        - regexp: '^.+$'
          containerImage: ooto-kmod:$KERNEL_FULL_VERSION
  selector:
    kubernetes.io/hostname: minikube
