---
apiVersion: ooto.sigs.k8s.io/v1beta1
kind: Module
metadata:
  name: ooto-ci-build
spec:
  driverContainer:
    name: overwritten-anyway
    command: [sleep, infinity]
    lifecycle:
      postStart:
        exec:
          command: [modprobe, -vd, /opt, ooto_ci_a]
      preStop:
        exec:
          command: [modprobe, -rvd, /opt, ooto_ci_a]
    securityContext:
      capabilities:
        add: [SYS_MODULE]
  kernelMappings:
    - literal: KVER_CHANGEME
      containerImage: registry.minikube/ooto-kmod:local
      build:
        pull:
          insecure: true
        push:
          insecure: true
        dockerfile: FROM registry.minikube/ooto-base:local
  selector:
    kubernetes.io/hostname: minikube
