name: Container image

on:
  push:
    tags: ['*']
    branches: [main]

jobs:
  build-push:
    name: Build and push
    runs-on: ubuntu-latest

    permissions:
      packages: write

    steps:
      - name: Generate image metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/qbarrand/oot-operator
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}